[package]
name = "crystal-shim-settings"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
publish = false

[dependencies]
crystal-shim-core = { path = "../core" }
edge-http = { version = "=0.8.0", default-features = false, features = ["io"] }
embedded-io-async = { version = "=0.7.0", default-features = false }
embassy-futures = "0.1"
heapless = "0.8"
subtle = { version = "=2.6.1", default-features = false }
zeroize = { version = "=1.9.0", default-features = false }
