M48
; DRILL file KiCad 10.0.5 date 2026-09-14T01:27:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T01:27:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X168.32Y-75.0
X168.32Y-93.0
T2
X32.0Y-52.0
X32.0Y-148.0
X168.0Y-52.0
X168.0Y-148.0
M30
